enum_entry(UNORM_R8)
enum_entry(SNORM_R8)

enum_entry(UNORM_R8G8B8)
enum_entry(SNORM_R8G8B8)

enum_entry(UNORM_R8G8B8A8)
enum_entry(SNORM_R8G8B8A8)

enum_entry(UNORM_B8G8R8)
enum_entry(SNORM_B8G8R8)

enum_entry(UNORM_B8G8R8A8)
enum_entry(SNORM_B8G8R8A8)

enum_entry(UNORM_R16G16B16)
enum_entry(SNORM_R16G16B16)
enum_entry(SFLOAT_R16G16B16)

enum_entry(UNORM_R16G16B16A16)
enum_entry(SNORM_R16G16B16A16)
enum_entry(SFLOAT_R16G16B16A16)

enum_entry(SFLOAT_R32G32B32A32)

enum_entry(UNORM_D24_UINT_S8)
enum_entry(UNORM_D16)
enum_entry(SFLOAT_D32)
enum_entry(Undefined)